"""Shared constants for the Kluky MCP server."""

SERVICE_NAME = "kluky_mcp"

CHARACTER_LIMIT = 12_000
NOT_IMPLEMENTED_PREFIX = "NOT_IMPLEMENTED"

API_BASE_URL_ENV = "KLUKY_API_BASE_URL"
API_KEY_ENV = "KLUKY_API_KEY"
REQUEST_TIMEOUT_SECONDS = 30.0
